apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::399547196114:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-T2VK8DSIBSXT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::399547196114:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LZOM1LX2SYU8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::399547196114:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-07T22:28:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1791"
  uid: ac857c0f-cc66-4c8e-8fbc-859e622a6f98
